### ISSUE TITLE
creating stormmonodocker_supervisor_1 error

### ISSUE THREAD

**Issue by zhbigbin** [ziyunhx/storm-mono-docker#2]
when I run 

> docker-compose up -d

appears errors like this:

> Creating stormmonodocker_supervisor_1
ERROR: for supervisor  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: for ui  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 113, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 56, in handle_connection_errors
    log_timeout_error()
TypeError: log_timeout_error() takes exactly 1 argument (0 given)

docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
please give me some suggest to resolve the problem,thank you !

**Comment by ziyunhx** [comment]
please make sure your network is available to access docker.
